import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter as Router} from 'react-router-dom';
import _app from './_app';
import Head from "next/head";

// const container = document.getElementById('root');
// const root = createRoot(container);
//
// root.render(
//   <Router>
//     <_app />
//   </Router>
// );

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h2>
                메인 페이지 입니다.
            </h2>
        </>
    );
}
